### ISSUE TITLE
East Germany

### ISSUE THREAD

**Issue by nueh** [MikeTaylor/palaeo-archbishop#1]
> Historical background
> 
> The German East Africa Expeditions
> 
> Between the years of 1907 and 1913, the Humboldt Museum für Naturkunde in what was then **East Berlin, East Germany**

Hello Mike,

_East Germany_ (aka  German Democratic Republic) and therefore _East Berlin_ existed from 1949 to 1990. You probably mean the German Empire.

**Comment by MikeTaylor** [comment]
Ha, excellent point, thank you! Fixed in https://github.com/MikeTaylor/palaeo-archbishop/commit/f2a5d53de65fc39eb5c1f43d04f3f09f107387ed
