### ISSUE TITLE
Confusing paragraph

### ISSUE THREAD

**Issue by HeinrichMallison** [MikeTaylor/palaeo-archbishop#6]
"This assignment raises a difficulty: ...."

It remains unclear, what said difficulty is! Do you mean that M. measured the length in an unusual way? Rework to make clear what the issue is.

**Comment by MikeTaylor** [comment]
Fixed in https://github.com/MikeTaylor/palaeo-archbishop/commit/1307c6493793fe07fa0822aed2ba5b5a292925d7
